import { useState, useEffect } from 'react';
import { GEMINI_API_KEY } from '../config/constants';

interface InPageAiModalProps {
    isOpen: boolean;
    onClose: () => void;
    initialPrompt: string;
}

const InPageAiModal = ({ isOpen, onClose, initialPrompt }: InPageAiModalProps) => {
    const [prompt, setPrompt] = useState(initialPrompt || '');
    const [isLoading, setIsLoading] = useState(false);
    const [result, setResult] = useState<{ type: string; content: string } | null>(null);
    const [error, setError] = useState('');

    useEffect(() => {
        if (isOpen && initialPrompt) {
            setPrompt(initialPrompt);
            handleExecutePrompt(initialPrompt);
        } else if (!isOpen) {
            setPrompt(''); setResult(null); setError(''); setIsLoading(false);
        }
    }, [isOpen, initialPrompt]);

    const isImagePrompt = (p: string) => {
        const imageKeywords = ['image', 'draw', 'generate an image', 'picture', 'photo', 'create a photo', 'paint'];
        return imageKeywords.some(keyword => p.toLowerCase().includes(keyword));
    };

    const handleExecutePrompt = async (currentPrompt: string) => {
        if (!currentPrompt.trim()) return;
        if (!GEMINI_API_KEY) {
            setError("API Key is missing. Please add your Gemini API key to the code.");
            return;
        }

        setIsLoading(true); setResult(null); setError('');

        try {
            const modelApiUrl = isImagePrompt(currentPrompt)
                ? `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-002:predict?key=${GEMINI_API_KEY}`
                : `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key=${GEMINI_API_KEY}`;

            const payload = isImagePrompt(currentPrompt)
                ? { instances: [{ prompt: currentPrompt }], parameters: { "sampleCount": 1 } }
                : { contents: [{ parts: [{ text: currentPrompt }] }] };

            const response = await fetch(modelApiUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(errorData.error?.message || `API Error: ${response.status}`);
            }

            const data = await response.json();

            if (isImagePrompt(currentPrompt)) {
                const base64Image = data.predictions?.[0]?.bytesBase64Encoded;
                if (base64Image) {
                    setResult({ type: 'image', content: `data:image/png;base64,${base64Image}` });
                } else {
                    throw new Error('Image data not found in API response.');
                }
            } else {
                const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
                if (text) {
                    setResult({ type: 'text', content: text });
                } else {
                    throw new Error('Text content not found in API response.');
                }
            }
        } catch (err) {
            setError((err as Error).message);
        } finally {
            setIsLoading(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <div onClick={onClose} className="absolute inset-0 bg-black/60 backdrop-blur-sm"></div>
            <div className="relative w-full max-w-2xl bg-white dark:bg-slate-900 rounded-2xl shadow-xl p-6 transform transition-all h-full max-h-[85vh] flex flex-col">
                <button onClick={onClose} className="absolute top-4 right-4 text-slate-500 hover:text-slate-800 dark:hover:text-slate-200" aria-label="Close">
                     <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
                <h2 className="text-xl font-bold mb-4 flex-shrink-0">AI Execution Hub</h2>
                <div className="flex-grow overflow-y-auto p-4 bg-slate-100 dark:bg-slate-800 rounded-lg min-h-0">
                    {isLoading && <div className="text-center p-8">Generating response...</div>}
                    {error && <div className="text-red-500 p-4">Error: {error}</div>}
                    {result && (
                        <div>
                            {result.type === 'text' && <p className="whitespace-pre-wrap">{result.content}</p>}
                            {result.type === 'image' && <img src={result.content} alt="Generated by AI" className="rounded-lg max-w-full mx-auto" />}
                        </div>
                    )}
                </div>
                <div className="mt-4 flex gap-2 flex-shrink-0">
                    <input
                        type="text"
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        onKeyUp={(e) => e.key === 'Enter' && handleExecutePrompt(prompt)}
                        placeholder="Enter your prompt here..."
                        className="flex-grow bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                    <button onClick={() => handleExecutePrompt(prompt)} disabled={isLoading} className="bg-indigo-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-indigo-700 disabled:bg-indigo-400">
                        {isLoading ? '...' : 'Go'}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default InPageAiModal;
